# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-26 13:40
from __future__ import unicode_literals

from django.db import migrations
import csv


def datareview(apps, schema_editor):
    Rater = apps.get_model('moviereviewapp', 'Rater')
    Movie = apps.get_model('moviereviewapp', 'Movie')
    Review = apps.get_model('moviereviewapp', 'Review')
    with open('/Users/chucklapress/tiy-projects/movie_review/movie_review/u.data', 'r') as inFile:
        data = csv.reader(inFile, delimiter='\t')
        for row in data:
            temp_rater = Rater.objects.get(id=row[0])
            temp_movie = Movie.objects.get(id=row[1])
            Review.objects.create(rater=temp_rater, movie=temp_movie, rating=row[2], timestamp=row[3])




class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewapp', '0003_auto_20161126_1335'),
    ]

    operations = [
    migrations.RunPython(datareview),
    ]
