# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviewapp', '0004_auto_20160614_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ratings', models.IntegerField()),
                ('average', models.FloatField()),
                ('movie_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviereviewapp.Movie')),
            ],
        ),
    ]
