# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    

    dependencies = [
        ('moviereviewapp', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='number_ratings',
            field=models.IntegerField(null=True),
        ),
    ]
