# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    


    dependencies = [
        ('moviereviewapp', '0006_auto_20160722_1402'),
    ]

    operations = [
    ]
